imports:
  - { resource: "EXT:ameos_scim/Configuration/Mapping/Frontend/DefaultUser.yaml" }
  - { resource: "EXT:ameos_scim/Configuration/Mapping/Frontend/DefaultGroup.yaml" }
  - { resource: "EXT:ameos_scim/Configuration/Mapping/Backend/DefaultUser.yaml" }
  - { resource: "EXT:ameos_scim/Configuration/Mapping/Backend/DefaultGroup.yaml" }