services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ameos\AmeosScim\:
    resource: '../Classes/*'

  Ameos\AmeosScim\Controller\UserController:
    public: true

  Ameos\AmeosScim\Controller\GroupController:
    public: true

  Ameos\AmeosScim\Controller\BulkController:
    public: true

  Ameos\AmeosScim\Controller\SchemaController:
    public: true

  Ameos\AmeosScim\CustomObject\GroupObject:
    public: true

  Ameos\AmeosScim\CustomObject\MultiValuedObject:
    public: true

  Ameos\AmeosScim\CustomObject\MemberObject:
    public: true

  Ameos\AmeosScim\EventListener\ProcessMembersAfterGroupPersist:
    tags:
      - name: event.listener
        identifier: 'scim/process-members'

  Ameos\AmeosScim\EventListener\CleanUsersAfterGroupRemoved:
    tags:
      - name: event.listener
        identifier: 'scim/clean-users'

  Ameos\AmeosScim\EventListener\CleanGroupsAfterGroupRemoved:
    tags:
      - name: event.listener
        identifier: 'scim/clean-groups'

  Ameos\AmeosScim\ConfigurationModuleProvider\ScimConfigurationProvider:       
    tags:
      - name: 'lowlevel.configuration.module.provider'
        identifier: 'scimConfigurationProvider'
        label: 'LLL:EXT:ameos_scim/Resources/Private/Language/locallang.xlf:scimConfigurationProvider'