services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ameos\Scim\:
    resource: '../Classes/*'

  Ameos\Scim\Controller\Frontend\UserController:
    public: true

  Ameos\Scim\Controller\Frontend\GroupController:
    public: true

  Ameos\Scim\Controller\Backend\UserController:
    public: true

  Ameos\Scim\Controller\Backend\GroupController:
    public: true

  Ameos\Scim\CustomObject\GroupObject:
    public: true

  Ameos\Scim\CustomObject\MultiValuedObject:
    public: true

  Ameos\Scim\CustomObject\MemberObject:
    public: true

  Ameos\Scim\EventListener\ProcessMembersAfterGroupPersist:
    tags:
      - name: event.listener
        identifier: 'scim/process-members'

  Ameos\Scim\EventListener\CleanUsersAfterGroupRemoved:
    tags:
      - name: event.listener
        identifier: 'scim/clean-users'